os:
  - linux

language: go

go:
  - 1.13.x

env:
  global:
    - GOTFLAGS="-race"
    - GO111MODULE=on
  matrix:
    - BUILD_DEPTYPE=gomod


# disable travis install
install:
  - (cd /tmp && go get github.com/ipfs/go-ipfs/cmd/ipfs@v0.6.0)

script:
  - bash <(curl -s https://raw.githubusercontent.com/ipfs/ci-helpers/master/travis-ci/run-standard-tests.sh)

cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build

notifications:
  email: false
